import pyochain as pc

from .._utils import Builtins, CollectionsABC, DuckDB, Pql, Pyochain, Typing


def header() -> str:
    return f'''
"""DuckDB Relation wrapper using SqlExpr instead of duckdb.Expression.

This file is AUTO-GENERATED by ``scripts/_core_generator.py``
Do not edit manually.
"""

from __future__ import annotations

from {Typing.module()} import TYPE_CHECKING, {Typing.ANY}, {Typing.LITERAL}, {Typing.SELF}, {Typing.SUPPORTS_INT}, {Typing.OVERLOAD}

import {DuckDB.module()}
import {Pyochain.module()} as pc
from {DuckDB.module()} import ExplainType, RenderMode
from .._core import {Pql.CORE_HANDLER}, {Pql.REL_HANDLER}, {Pql.TRY_ITER}, {Pql.INTO_DUCKDB}, {Pql.DUCK_HANDLER}
if TYPE_CHECKING:
    from {CollectionsABC.module()} import {CollectionsABC.CALLABLE}, {CollectionsABC.ITERABLE}
    import numpy as np
    import pandas  # pyright: ignore[reportMissingModuleSource]
    import polars
    import pyarrow as pa
    import torch
    import tensorflow  # pyright: ignore[reportMissingModuleSource]
    from {DuckDB.module()} import sqltypes
    from {Typing.module()} import {Typing.UNION}

    type ParquetFieldIdsType = {Builtins.DICT}[{Builtins.STR}, {Builtins.INT} | ParquetFieldIdsType]
'''


PYTYPING_REWRITES = pc.Dict.from_ref(
    {
        "pytyping.Any": Typing.ANY,
        "pytyping.SupportsInt": Typing.SUPPORTS_INT,
        "pytyping.List": Builtins.LIST,
        "pytyping.Literal": Typing.LITERAL,
        "pytyping.Union": Typing.UNION,
        "pytorch": "torch",
        "pyarrow.lib.": "pa.",
        "pyarrow.": "pa.",
    }
)

TYPE_SUBS = pc.Dict({DuckDB.EXPRESSION: Pql.DUCK_HANDLER, DuckDB.RELATION: Typing.SELF})

EXPR_TYPE_SUBS = pc.Dict(
    {DuckDB.EXPRESSION: Typing.SELF, DuckDB.RELATION: Pql.RELATION}
)


PARAM_TYPE_FIXES = pc.Dict.from_kwargs(
    aggregate=pc.Dict.from_kwargs(
        aggr_expr=f"{DuckDB.EXPRESSION} | {Builtins.STR} | {CollectionsABC.ITERABLE}[{DuckDB.EXPRESSION} | {Builtins.STR}]"
    )
)

RETURN_TYPE_FIXES = pc.Dict.from_kwargs(
    dtypes=f"{Builtins.LIST}[sqltypes.DuckDBPyType]"
)

KW_ONLY_FIXES = pc.Set({"write_csv", "write_parquet"})
