import pyochain as pc

from .._utils import (
    Builtins,
    CollectionsABC,
    DuckDB,
    From,
    Import,
    Pql,
    Pyochain,
    Typing,
)


def header() -> str:
    return f'''
"""DuckDB Relation wrapper using SqlExpr instead of duckdb.Expression.

This file is AUTO-GENERATED by ``scripts/_core_generator.py``
Do not edit manually.
"""

from __future__ import annotations

{From(Typing).import_(Typing.TYPE_CHECKING, Typing.ANY, Typing.LITERAL, Typing.SELF, Typing.SUPPORTS_INT, Typing.OVERLOAD)}
{Import(DuckDB)}
{Import(Pyochain).as_("pc")}
{From(DuckDB).import_(DuckDB.EXPLAIN_TYPE, DuckDB.RENDER_MODE)}
from .._core import {Pql.CORE_HANDLER}, {Pql.REL_HANDLER}, {Pql.TRY_ITER}, {Pql.INTO_DUCKDB}, {Pql.DUCK_HANDLER}
if {Typing.TYPE_CHECKING}:
    {From(CollectionsABC).import_(CollectionsABC.CALLABLE, CollectionsABC.ITERABLE)}
    import numpy as np
    import pandas  # pyright: ignore[reportMissingModuleSource]
    import polars
    import pyarrow as pa
    import torch
    import tensorflow  # pyright: ignore[reportMissingModuleSource]
    {From(DuckDB).import_(DuckDB.SQLTYPES)}
    {From(Typing).import_(Typing.UNION)}

    type ParquetFieldIdsType = {Builtins.DICT}[{Builtins.STR}, {Builtins.INT} | ParquetFieldIdsType]
'''


PYTYPING_REWRITES = pc.Dict.from_ref(
    {
        "pytyping.Any": Typing.ANY,
        "pytyping.SupportsInt": Typing.SUPPORTS_INT,
        "pytyping.List": Builtins.LIST,
        "pytyping.Literal": Typing.LITERAL,
        "pytyping.Union": Typing.UNION,
        "pytorch": "torch",
        "pyarrow.lib.": "pa.",
        "pyarrow.": "pa.",
    }
)

TYPE_SUBS = pc.Dict({DuckDB.EXPRESSION: Pql.DUCK_HANDLER, DuckDB.RELATION: Typing.SELF})

EXPR_TYPE_SUBS = pc.Dict(
    {DuckDB.EXPRESSION: Typing.SELF, DuckDB.RELATION: Pql.RELATION}
)


PARAM_TYPE_FIXES = pc.Dict.from_kwargs(
    aggregate=pc.Dict.from_kwargs(
        aggr_expr=DuckDB.EXPRESSION.into_union(
            Builtins.STR,
            CollectionsABC.ITERABLE.of_type(DuckDB.EXPRESSION, Builtins.STR),
        )
    )
)

RETURN_TYPE_FIXES = pc.Dict.from_kwargs(
    dtypes=Builtins.LIST.of_type("sqltypes.DuckDBPyType")
)

KW_ONLY_FIXES = pc.Set({"write_csv", "write_parquet"})
