from enum import StrEnum, auto

import pyochain as pc


class PyLit(StrEnum):
    INTO_DUCKDB = auto()
    RELATION = "Relation"
    REL_HANDLER = "RelHandler"
    DUCK_HANDLER = "DuckHandler"
    DUCK_REL = "DuckDBPyRelation"
    DUCK_EXPR = "Expression"
    ITERABLE = "Iterable"
    NONE = "None"
    ANY = "Any"
    SELF_RET = "Self"
    LITERAL = "Literal"
    LIST = auto()
    DICT = auto()
    OVERLOAD = auto()
    PROPERTY = auto()
    SELF = auto()
    STR = auto()

    @classmethod
    def header(cls) -> str:
        return f'''
"""DuckDB Relation wrapper using SqlExpr instead of duckdb.Expression.

This file is AUTO-GENERATED by ``scripts/_core_generator.py``
Do not edit manually.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, {cls.ANY}, {cls.LITERAL}, {cls.SELF_RET}, SupportsInt, {cls.OVERLOAD}

import duckdb
import pyochain as pc
from duckdb import ExplainType, RenderMode
from .._core import ExprHandler, {cls.REL_HANDLER}, try_iter, into_duckdb, {cls.DUCK_HANDLER}
if TYPE_CHECKING:
    from collections.abc import Callable, {cls.ITERABLE}
    import numpy as np
    import pandas  # pyright: ignore[reportMissingModuleSource]
    import polars
    import pyarrow as pa
    import torch
    import tensorflow  # pyright: ignore[reportMissingModuleSource]
    from duckdb import sqltypes
    from typing import Union

    type ParquetFieldIdsType = {cls.DICT}[str, int | ParquetFieldIdsType]
'''


PYTYPING_REWRITES = pc.Dict.from_ref(
    {
        "pytyping.Any": PyLit.ANY,
        "pytyping.SupportsInt": "SupportsInt",
        "pytyping.List": PyLit.LIST,
        "pytyping.Literal": PyLit.LITERAL,
        "pytyping.Union": "Union",
        "pytorch": "torch",
        "pyarrow.lib.": "pa.",
        "pyarrow.": "pa.",
    }
)

TYPE_SUBS = pc.Dict(
    {
        PyLit.DUCK_EXPR: PyLit.DUCK_HANDLER,
        PyLit.DUCK_REL: PyLit.SELF_RET,
    }
)

EXPR_TYPE_SUBS = pc.Dict(
    {
        PyLit.DUCK_EXPR: PyLit.SELF_RET,
        PyLit.DUCK_REL: PyLit.RELATION,
    }
)


PARAM_TYPE_FIXES = pc.Dict.from_kwargs(
    aggregate=pc.Dict.from_kwargs(
        aggr_expr=f"{PyLit.DUCK_EXPR} | {PyLit.STR} | {PyLit.ITERABLE}[{PyLit.DUCK_EXPR} | {PyLit.STR}]"
    )
)

RETURN_TYPE_FIXES = pc.Dict.from_kwargs(dtypes=f"{PyLit.LIST}[sqltypes.DuckDBPyType]")

KW_ONLY_FIXES = pc.Set({"write_csv", "write_parquet"})
