from textwrap import dedent

from .._utils import (
    CollectionsABC,
    DuckDB,
    From,
    Import,
    Pql,
    Pyochain,
    Typing,
)


def header() -> str:
    return f'''
"""DuckDB Relation/Expression wrappers with pql typing adapters.

This file is AUTO-GENERATED by ``scripts/_core_generator.py``
Do not edit manually.
"""

from __future__ import annotations

{From(Typing).import_(Typing.TYPE_CHECKING, Typing.ANY, Typing.LITERAL, Typing.SELF, Typing.SUPPORTS_INT, Typing.OVERLOAD, Typing.CLASSVAR)}
{Import(DuckDB)}
{Import(Pyochain).as_("pc")}
{From(DuckDB).import_(DuckDB.EXPLAIN_TYPE, DuckDB.RENDER_MODE, DuckDB.RELATION)}
from .._core import {Pql.CORE_HANDLER}, {Pql.REL_HANDLER}, {Pql.INTO_DUCKDB}, {Pql.INTO_DUCKDB_MAPPING}, {Pql.DUCK_HANDLER}
from ..utils import {Pql.TRY_ITER}
if {Typing.TYPE_CHECKING}:
    {From(CollectionsABC).import_(CollectionsABC.CALLABLE, CollectionsABC.ITERABLE, CollectionsABC.MAPPING)}

    import numpy as np
    import pandas
    import polars
    import pyarrow as pa
    from _duckdb._enums import (  # pyright: ignore[reportMissingModuleSource]
        ExplainTypeLiteral,
        RenderModeLiteral,
    )
    from _duckdb._typing import (  # pyright: ignore[reportMissingModuleSource]
        CsvCompression,
        CsvEncoding,
        IntoPyType,
        JoinType,
        ParquetCompression,
        ParquetFieldsOptions,
        StrIntoPyType,
    )
    {From(DuckDB).import_(DuckDB.SQLTYPES)}

    from ..typing import {Pql.INTO_EXPR}, {Pql.INTO_EXPR_COLUMN}, {Pql.PYTHON_LITERAL}
'''


def class_def(wrapper_class: str, wrapper_base: str, stub_class: str) -> str:
    return dedent(f'''

class {wrapper_class}({wrapper_base}):
    """Wrapper around {stub_class} that uses SqlExpr instead of duckdb.Expression.

    This is a composition-based wrapper: it stores a ``_expr: {stub_class}``
    and delegates all method calls, converting SqlExpr <-> duckdb.Expression
    at the boundary.
    """

    __slots__: ClassVar[Iterable[str]] = ()

    ''')
