from textwrap import dedent

from .._utils import (
    Builtins,
    CollectionsABC,
    DuckDB,
    From,
    Import,
    Pql,
    Pyochain,
    Typing,
)


def header() -> str:
    return f'''
"""DuckDB Relation wrapper using SqlExpr instead of duckdb.Expression.

This file is AUTO-GENERATED by ``scripts/_core_generator.py``
Do not edit manually.
"""

from __future__ import annotations

{From(Typing).import_(Typing.TYPE_CHECKING, Typing.ANY, Typing.LITERAL, Typing.SELF, Typing.SUPPORTS_INT, Typing.OVERLOAD)}
{Import(DuckDB)}
{Import(Pyochain).as_("pc")}
{From(DuckDB).import_(DuckDB.EXPLAIN_TYPE, DuckDB.RENDER_MODE)}
from .._core import {Pql.CORE_HANDLER}, {Pql.REL_HANDLER}, {Pql.INTO_DUCKDB}, {Pql.DUCK_HANDLER}
from ..._args_iter import {Pql.TRY_ITER}
if {Typing.TYPE_CHECKING}:
    {From(CollectionsABC).import_(CollectionsABC.CALLABLE, CollectionsABC.ITERABLE)}
    import numpy as np
    import pandas  # pyright: ignore[reportMissingModuleSource]
    import polars
    import pyarrow as pa
    {From(DuckDB).import_(DuckDB.SQLTYPES)}
    {From(Typing).import_(Typing.UNION)}

    type ParquetFieldIdsType = {Builtins.DICT}[{Builtins.STR}, {Builtins.INT} | ParquetFieldIdsType]
'''


def class_def(wrapper_class: str, wrapper_base: str, stub_class: str) -> str:
    return dedent(f'''

class {wrapper_class}({wrapper_base}):
    """Wrapper around {stub_class} that uses SqlExpr instead of duckdb.Expression.

    This is a composition-based wrapper: it stores a ``_expr: {stub_class}``
    and delegates all method calls, converting SqlExpr <-> duckdb.Expression
    at the boundary.
    """

    __slots__ = ()

    ''')
