def header() -> str:
    return '''\
"""DuckDB Relation wrapper using SqlExpr instead of duckdb.Expression.

This file is AUTO-GENERATED by ``scripts/_rel_generator.py``
Do not edit manually.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal, Self, SupportsInt, overload

import duckdb
from duckdb import ExplainType, RenderMode
from ._core import ExprHandler, RelHandler
from ._expr import SqlExpr, into_duckdb
if TYPE_CHECKING:
    from collections.abc import Callable
    import numpy as np
    import pandas  # pyright: ignore[reportMissingModuleSource]
    import polars
    import pyarrow as pa
    import torch
    import tensorflow  # pyright: ignore[reportMissingModuleSource]
    from duckdb import sqltypes
    from typing import Union

    type ParquetFieldIdsType = dict[str, int | ParquetFieldIdsType]
'''


def class_def() -> str:
    return '''

class Relation(RelHandler):
    """Wrapper around DuckDBPyRelation that uses SqlExpr instead of duckdb.Expression.

    This is a composition-based wrapper: it stores a ``_expr: DuckDBPyRelation``
    and delegates all method calls, converting SqlExpr <-> duckdb.Expression
    at the boundary.
    """

    __slots__ = ()

'''
