"""Generate typed SQL function wrappers from DuckDB introspection."""

from __future__ import annotations

import subprocess
from functools import partial
from pathlib import Path
from textwrap import dedent
from typing import Annotated

import pyochain as pc
import typer

from ._query import get_df, sql_query
from ._sections import FunctionInfo, sections

DEFAULT_OUTPUT = Path("src", "pql", "sql", "fns.py")

app = typer.Typer(add_completion=False)


@app.command()
def main(
    output: Annotated[Path, typer.Option("--output", "-o")] = DEFAULT_OUTPUT,
) -> None:
    """Generate typed DuckDB function wrappers."""
    typer.echo("Fetching functions from DuckDB...")
    content = _run_pipeline()

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    typer.echo(f"Generated {output}")
    _run_ruff(output)
    typer.echo("Done!")


@app.command()
def explore() -> None:
    """Explore data from the table."""
    return (
        sql_query().pl(lazy=True).select("return_type").drop_nulls().unique().show(100)
    )


def _run_ruff(output: Path) -> None:
    typer.echo("Running Ruff checks and format...")
    uv_args = ("uv", "run", "ruff")
    run_ruff = partial(subprocess.run, check=False)
    run_ruff((*uv_args, "check", "--fix", "--unsafe-fixes", str(output)))
    run_ruff((*uv_args, "format", str(output)))


def _run_pipeline() -> str:
    return (
        get_df()
        .pipe(lambda df: pc.Iter(df.iter_rows()))
        .map(FunctionInfo.from_row)
        .collect()
        .inspect(lambda fns: typer.echo(f"Found {fns.length()} function signatures"))
        .into(_build_file)
    )


def _build_file(fns: pc.Seq[FunctionInfo]) -> str:
    all_names = fns.iter().map(lambda f: f'    "{f.python_name}",').join("\n")
    return f"{_header()}{all_names}\n]{sections(fns)}\n"


def _header() -> str:
    return dedent('''\
        """DuckDB SQL function wrappers with type hints.

        This file is AUTO-GENERATED by scripts/generate_fns.py
        Do not edit manually - regenerate with:
            uv run scripts/generate_fns.py

        Functions are extracted from DuckDB's duckdb_functions() introspection.
        """

        from __future__ import annotations

        from datetime import date, datetime, time, timedelta

        from ._exprs import SqlExpr, func

        __all__ = [
    ''')


if __name__ == "__main__":
    app()
