from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import pyochain as pc

MANUAL_FNS_PATH = Path("src", "pql", "sql", "_manual_fns.py")


@dataclass(slots=True)
class FunctionInfo:
    """Container for pre-formatted function parts."""

    category: str
    python_name: str
    func: str


def build_file(fns: pc.Seq[FunctionInfo]) -> str:

    sections = (
        fns.iter()
        .group_by(lambda f: f.category)
        .map_star(
            lambda category, funcs: (
                f"\n\n    # {'=' * 56}\n    # {category}\n    # {'=' * 56}\n\n"
                + funcs.map(lambda f: f.func).join("\n\n")
            )
        )
        .join("")
    )
    return f"{_header()}{sections}\n"


def _header() -> str:
    return dedent('''\
        """DuckDB SQL function wrappers with type hints.

        This file is AUTO-GENERATED by scripts/generate_fns.py
        Do not edit manually - regenerate with:
            uv run -m scripts.generator

        Functions are extracted from DuckDB's duckdb_functions() introspection.
        """

        from __future__ import annotations

        from datetime import date, datetime, time, timedelta
        from decimal import Decimal
        from typing import TYPE_CHECKING, Self

        from ._core import func

        if TYPE_CHECKING:
            from duckdb import Expression as SqlExpr



        class FnsMixin:
            """Mixin providing all auto-generated DuckDB functions as methods.

            All methods return Self for chaining.
            """

            __slots__ = ("_expr",)

            def __init__(self, expr: SqlExpr) -> None:
                """Initialize mixin with underlying SqlExpr."""
                self._expr = expr
    ''')
