"""DuckDB Relation/Expression wrappers with pql typing adapters.

This file is AUTO-GENERATED by ``scripts/_core_generator.py``
Do not edit manually.
"""

from __future__ import annotations

from typing import (
    TYPE_CHECKING,
    Any,
    ClassVar,
    Literal,
    Self,
    SupportsInt,
    overload,
)

import pyochain as pc
from duckdb import DuckDBPyRelation, ExplainType, RenderMode

from .._core import CoreHandler, into_duckdb, into_duckdb_mapping
from ..utils import try_iter

if TYPE_CHECKING:
    from collections.abc import Callable, Iterable, Mapping

    import numpy as np
    import pandas as pd
    import polars as pl
    import pyarrow as pa
    from _duckdb._enums import (  # pyright: ignore[reportMissingModuleSource]
        ExplainTypeLiteral,
        RenderModeLiteral,
    )
    from _duckdb._typing import (  # pyright: ignore[reportMissingModuleSource]
        CsvCompression,
        CsvEncoding,
        JoinType,
        ParquetCompression,
        ParquetFieldsOptions,
        StrIntoPyType,
    )
    from duckdb import sqltypes

    from ..typing import IntoExpr, IntoExprColumn, PythonLiteral


class Relation(CoreHandler[DuckDBPyRelation]):
    """Wrapper around DuckDBPyRelation that uses SqlExpr instead of duckdb.Expression.

    This is a composition-based wrapper: it stores a ``_expr: DuckDBPyRelation``
    and delegates all method calls, converting SqlExpr <-> duckdb.Expression
    at the boundary.
    """

    __slots__: ClassVar[Iterable[str]] = ()

    def __arrow_c_stream__(self, requested_schema: object | None = None) -> Any:  # pyright: ignore[reportExplicitAny, reportAny]
        """Execute and return an ArrowArrayStream through the Arrow PyCapsule Interface.

        https://arrow.apache.org/docs/dev/format/CDataInterface/PyCapsuleInterface.html
        """
        return self.inner().__arrow_c_stream__(requested_schema)  # pyright: ignore[reportAny]

    def __contains__(self, name: str) -> bool:
        return self.inner().__contains__(name)

    def __getattr__(self, name: str) -> Self:
        """Get a projection relation created from this relation, on the provided column name."""
        return self._new(self.inner().__getattr__(name))

    def __getitem__(self, name: str) -> Self:
        """Get a projection relation created from this relation, on the provided column name."""
        return self._new(self.inner().__getitem__(name))

    def __len__(self) -> int:
        """Number of rows in relation."""
        return self.inner().__len__()

    def aggregate(
        self, aggr_expr: str | Iterable[IntoExpr], group_expr: IntoExpr = ""
    ) -> Self:
        """Compute the aggregate aggr_expr by the optional groups group_expr on the relation."""
        return self._new(
            self.inner().aggregate(
                try_iter(aggr_expr).map(into_duckdb), into_duckdb(group_expr)
            )
        )

    def any_value(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Returns the first non-null value from a given expression."""
        return self._new(
            self.inner().any_value(expression, groups, window_spec, projected_columns)
        )

    def apply(
        self,
        function_name: str,
        function_aggr: str,
        group_expr: str = "",
        function_parameter: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Compute the function of a single column or a list of columns by the optional groups on the relation."""
        return self._new(
            self.inner().apply(
                function_name,
                function_aggr,
                group_expr,
                function_parameter,
                projected_columns,
            )
        )

    def arg_max(
        self,
        arg_column: str,
        value_column: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Finds the row with the maximum value for a value column and returns the value of that row for an argument column."""
        return self._new(
            self.inner().arg_max(
                arg_column, value_column, groups, window_spec, projected_columns
            )
        )

    def arg_min(
        self,
        arg_column: str,
        value_column: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Finds the row with the minimum value for a value column and returns the value of that row for an argument column."""
        return self._new(
            self.inner().arg_min(
                arg_column, value_column, groups, window_spec, projected_columns
            )
        )

    def arrow(self, batch_size: SupportsInt = 1000000) -> pa.RecordBatchReader:
        """Alias of to_arrow_reader(). We recommend using to_arrow_reader() instead."""
        return self.inner().arrow(batch_size)

    def to_arrow_reader(
        self, batch_size: SupportsInt = 1000000
    ) -> pa.RecordBatchReader:
        """Execute and return an Arrow Record Batch Reader that yields all rows."""
        return self.inner().to_arrow_reader(batch_size)

    def to_arrow_table(self, batch_size: SupportsInt = 1000000) -> pa.Table:
        """Execute and fetch all rows as an Arrow Table."""
        return self.inner().to_arrow_table(batch_size)

    def avg(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the average of a given expression."""
        return self._new(
            self.inner().avg(expression, groups, window_spec, projected_columns)
        )

    def bit_and(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the bitwise AND of all bits present in a given expression."""
        return self._new(
            self.inner().bit_and(expression, groups, window_spec, projected_columns)
        )

    def bit_or(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the bitwise OR of all bits present in a given expression."""
        return self._new(
            self.inner().bit_or(expression, groups, window_spec, projected_columns)
        )

    def bit_xor(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the bitwise XOR of all bits present in a given expression."""
        return self._new(
            self.inner().bit_xor(expression, groups, window_spec, projected_columns)
        )

    def bitstring_agg(
        self,
        expression: str,
        min: int | None = None,
        max: int | None = None,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes a bitstring with bits set for each distinct value in a given expression."""
        return self._new(
            self.inner().bitstring_agg(
                expression, min, max, groups, window_spec, projected_columns
            )
        )

    def bool_and(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the logical AND of all values present in a given expression."""
        return self._new(
            self.inner().bool_and(expression, groups, window_spec, projected_columns)
        )

    def bool_or(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the logical OR of all values present in a given expression."""
        return self._new(
            self.inner().bool_or(expression, groups, window_spec, projected_columns)
        )

    def close(self) -> None:
        """Closes the result."""
        return self.inner().close()

    def count(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the number of elements present in a given expression."""
        return self._new(
            self.inner().count(expression, groups, window_spec, projected_columns)
        )

    def create(self, table_name: str) -> None:
        """Creates a new table named table_name with the contents of the relation object."""
        return self.inner().create(table_name)

    def create_view(self, view_name: str, replace: bool = True) -> Self:
        """Creates a view named view_name that refers to the relation object."""
        return self._new(self.inner().create_view(view_name, replace))

    def cross(self, other_rel: Self) -> Self:
        """Create cross/cartesian product of two relational objects."""
        return self._new(self.inner().cross(other_rel.inner()))

    def cume_dist(self, window_spec: str, projected_columns: str = "") -> Self:
        """Computes the cumulative distribution within the partition."""
        return self._new(self.inner().cume_dist(window_spec, projected_columns))

    def dense_rank(self, window_spec: str, projected_columns: str = "") -> Self:
        """Computes the dense rank within the partition."""
        return self._new(self.inner().dense_rank(window_spec, projected_columns))

    def describe(self) -> Self:
        """Gives basic statistics (e.g., min, max) and if NULL exists for each column of the relation."""
        return self._new(self.inner().describe())

    def df(self, *, date_as_object: bool = False) -> pd.DataFrame:
        """Execute and fetch all rows as a pandas DataFrame."""
        return self.inner().df(date_as_object=date_as_object)

    def distinct(self) -> Self:
        """Retrieve distinct rows from this relation object."""
        return self._new(self.inner().distinct())

    def except_(self, other_rel: Self) -> Self:
        """Create the set except of this relation object with another relation object in other_rel."""
        return self._new(self.inner().except_(other_rel.inner()))

    def execute(self) -> Self:
        """Transform the relation into a result set."""
        return self._new(self.inner().execute())

    def explain(
        self, type: ExplainType | ExplainTypeLiteral = ExplainType.STANDARD
    ) -> str:
        return self.inner().explain(type)

    def favg(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the average of all values present in a given expression using a more accurate floating point summation (Kahan Sum)."""
        return self._new(
            self.inner().favg(expression, groups, window_spec, projected_columns)
        )

    def fetch_arrow_reader(
        self, batch_size: SupportsInt = 1000000
    ) -> pa.RecordBatchReader:
        """Execute and return an Arrow Record Batch Reader that yields all rows."""
        return self.inner().fetch_arrow_reader(batch_size)

    def fetch_arrow_table(self, batch_size: SupportsInt = 1000000) -> pa.Table:
        """Execute and fetch all rows as an Arrow Table."""
        return self.inner().fetch_arrow_table(batch_size)

    def fetch_df_chunk(
        self, vectors_per_chunk: SupportsInt = 1, *, date_as_object: bool = False
    ) -> pd.DataFrame:
        """Execute and fetch a chunk of the rows."""
        return self.inner().fetch_df_chunk(
            vectors_per_chunk, date_as_object=date_as_object
        )

    def fetch_record_batch(
        self, rows_per_batch: SupportsInt = 1000000
    ) -> pa.RecordBatchReader:
        """Execute and return an Arrow Record Batch Reader that yields all rows."""
        return self.inner().fetch_record_batch(rows_per_batch)

    def fetchall(self) -> pc.Vec[tuple[Any, ...]]:  # pyright: ignore[reportExplicitAny]
        """Execute and fetch all rows as a list of tuples."""
        return pc.Vec.from_ref(self.inner().fetchall())

    def fetchdf(self, *, date_as_object: bool = False) -> pd.DataFrame:
        """Execute and fetch all rows as a pandas DataFrame."""
        return self.inner().fetchdf(date_as_object=date_as_object)

    def fetchmany(self, size: SupportsInt = 1) -> pc.Vec[tuple[Any, ...]]:  # pyright: ignore[reportExplicitAny]
        """Execute and fetch the next set of rows as a list of tuples."""
        return pc.Vec.from_ref(self.inner().fetchmany(size))

    def fetchnumpy(self) -> pc.Dict[str, np.typing.NDArray[Any] | pd.Categorical]:  # pyright: ignore[reportExplicitAny]
        """Execute and fetch all rows as a Python dict mapping each column to one numpy arrays."""
        return pc.Dict.from_ref(self.inner().fetchnumpy())

    def fetchone(self) -> tuple[Any, ...] | None:  # pyright: ignore[reportExplicitAny]
        """Execute and fetch a single row as a tuple."""
        return self.inner().fetchone()

    def filter(self, filter_expr: IntoExprColumn) -> Self:
        """Filter the relation object by the filter in filter_expr."""
        return self._new(self.inner().filter(into_duckdb(filter_expr)))

    def first(
        self, expression: str, groups: str = "", projected_columns: str = ""
    ) -> Self:
        """Returns the first value of a given expression."""
        return self._new(self.inner().first(expression, groups, projected_columns))

    def first_value(
        self, expression: str, window_spec: str = "", projected_columns: str = ""
    ) -> Self:
        """Computes the first value within the group or partition."""
        return self._new(
            self.inner().first_value(expression, window_spec, projected_columns)
        )

    def fsum(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the sum of all values present in a given expression using a more accurate floating point summation (Kahan Sum)."""
        return self._new(
            self.inner().fsum(expression, groups, window_spec, projected_columns)
        )

    def geomean(
        self, expression: str, groups: str = "", projected_columns: str = ""
    ) -> Self:
        """Computes the geometric mean over all values present in a given expression."""
        return self._new(self.inner().geomean(expression, groups, projected_columns))

    def histogram(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the histogram over all values present in a given expression."""
        return self._new(
            self.inner().histogram(expression, groups, window_spec, projected_columns)
        )

    def insert(self, values: list[object]) -> None:
        """Inserts the given values into the relation."""
        return self.inner().insert(values)

    def insert_into(self, table_name: str) -> None:
        """Inserts the relation object into an existing table named table_name."""
        return self.inner().insert_into(table_name)

    def intersect(self, other_rel: Self) -> Self:
        """Create the set intersection of this relation object with another relation object in other_rel."""
        return self._new(self.inner().intersect(other_rel.inner()))

    def join(
        self, other_rel: Self, condition: IntoExprColumn, how: JoinType = "inner"
    ) -> Self:
        """Join the relation object with another relation object in other_rel using the join condition expression in join_condition. Types supported are 'inner', 'left', 'right', 'outer', 'semi' and 'anti'."""
        return self._new(
            self.inner().join(other_rel.inner(), into_duckdb(condition), how)
        )

    def lag(
        self,
        expression: str,
        window_spec: str,
        offset: SupportsInt = 1,
        default_value: str = "NULL",
        ignore_nulls: bool = False,
        projected_columns: str = "",
    ) -> Self:
        """Computes the lag within the partition."""
        return self._new(
            self.inner().lag(
                expression,
                window_spec,
                offset,
                default_value,
                ignore_nulls,
                projected_columns,
            )
        )

    def last(
        self, expression: str, groups: str = "", projected_columns: str = ""
    ) -> Self:
        """Returns the last value of a given expression."""
        return self._new(self.inner().last(expression, groups, projected_columns))

    def last_value(
        self, expression: str, window_spec: str = "", projected_columns: str = ""
    ) -> Self:
        """Computes the last value within the group or partition."""
        return self._new(
            self.inner().last_value(expression, window_spec, projected_columns)
        )

    def lead(
        self,
        expression: str,
        window_spec: str,
        offset: SupportsInt = 1,
        default_value: str = "NULL",
        ignore_nulls: bool = False,
        projected_columns: str = "",
    ) -> Self:
        """Computes the lead within the partition."""
        return self._new(
            self.inner().lead(
                expression,
                window_spec,
                offset,
                default_value,
                ignore_nulls,
                projected_columns,
            )
        )

    def limit(self, n: SupportsInt, offset: SupportsInt = 0) -> Self:
        """Only retrieve the first n rows from this relation object, starting at offset."""
        return self._new(self.inner().limit(n, offset))

    def list(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Returns a list containing all values present in a given expression."""
        return self._new(
            self.inner().list(expression, groups, window_spec, projected_columns)
        )

    def map(
        self,
        map_function: Callable[..., PythonLiteral],
        *,
        schema: dict[str, sqltypes.DuckDBPyType] | None = None,
    ) -> Self:
        """Calls the passed function on the relation."""
        return self._new(self.inner().map(map_function, schema=schema))

    def max(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Returns the maximum value present in a given expression."""
        return self._new(
            self.inner().max(expression, groups, window_spec, projected_columns)
        )

    def mean(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the average of a given expression."""
        return self._new(
            self.inner().mean(expression, groups, window_spec, projected_columns)
        )

    def median(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the median over all values present in a given expression."""
        return self._new(
            self.inner().median(expression, groups, window_spec, projected_columns)
        )

    def min(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Returns the minimum value present in a given expression."""
        return self._new(
            self.inner().min(expression, groups, window_spec, projected_columns)
        )

    def mode(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the mode over all values present in a given expression."""
        return self._new(
            self.inner().mode(expression, groups, window_spec, projected_columns)
        )

    def n_tile(
        self, window_spec: str, num_buckets: SupportsInt, projected_columns: str = ""
    ) -> Self:
        """Divides the partition as equally as possible into num_buckets."""
        return self._new(
            self.inner().n_tile(window_spec, num_buckets, projected_columns)
        )

    def nth_value(
        self,
        expression: str,
        window_spec: str,
        offset: SupportsInt,
        ignore_nulls: bool = False,
        projected_columns: str = "",
    ) -> Self:
        """Computes the nth value within the partition."""
        return self._new(
            self.inner().nth_value(
                expression, window_spec, offset, ignore_nulls, projected_columns
            )
        )

    def order(self, order_expr: str) -> Self:
        """Reorder the relation object by order_expr."""
        return self._new(self.inner().order(order_expr))

    def percent_rank(self, window_spec: str, projected_columns: str = "") -> Self:
        """Computes the relative rank within the partition."""
        return self._new(self.inner().percent_rank(window_spec, projected_columns))

    @overload
    def pl(
        self, batch_size: SupportsInt = 1000000, *, lazy: Literal[False] = ...
    ) -> pl.DataFrame: ...

    @overload
    def pl(
        self, batch_size: SupportsInt = 1000000, *, lazy: Literal[True]
    ) -> pl.LazyFrame: ...

    def pl(
        self, batch_size: SupportsInt = 1000000, *, lazy: bool = False
    ) -> pl.DataFrame | pl.LazyFrame:
        """Execute and fetch all rows as a Polars DataFrame."""
        return self.inner().pl(batch_size, lazy=lazy)

    def product(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Returns the product of all values present in a given expression."""
        return self._new(
            self.inner().product(expression, groups, window_spec, projected_columns)
        )

    def project(self, *args: IntoExpr, groups: str = "") -> Self:
        """Project the relation object by the projection in project_expr."""
        return self._new(
            self.inner().project(*pc.Iter(args).map(into_duckdb), groups=groups)
        )

    def quantile(
        self,
        expression: str,
        q: float | list[float] = 0.5,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the exact quantile value for a given expression."""
        return self._new(
            self.inner().quantile(expression, q, groups, window_spec, projected_columns)
        )

    def quantile_cont(
        self,
        expression: str,
        q: float | list[float] = 0.5,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the interpolated quantile value for a given expression."""
        return self._new(
            self.inner().quantile_cont(
                expression, q, groups, window_spec, projected_columns
            )
        )

    def quantile_disc(
        self,
        expression: str,
        q: float | list[float] = 0.5,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the exact quantile value for a given expression."""
        return self._new(
            self.inner().quantile_disc(
                expression, q, groups, window_spec, projected_columns
            )
        )

    def query(self, virtual_table_name: str, sql_query: str) -> Self:
        """Run the given SQL query in sql_query on the view named virtual_table_name that refers to the relation object."""
        return self._new(self.inner().query(virtual_table_name, sql_query))

    def rank(self, window_spec: str, projected_columns: str = "") -> Self:
        """Computes the rank within the partition."""
        return self._new(self.inner().rank(window_spec, projected_columns))

    def rank_dense(self, window_spec: str, projected_columns: str = "") -> Self:
        """Computes the dense rank within the partition."""
        return self._new(self.inner().rank_dense(window_spec, projected_columns))

    def row_number(self, window_spec: str, projected_columns: str = "") -> Self:
        """Computes the row number within the partition."""
        return self._new(self.inner().row_number(window_spec, projected_columns))

    def select(self, *args: IntoExpr, groups: str = "") -> Self:
        """Project the relation object by the projection in project_expr."""
        return self._new(
            self.inner().select(*pc.Iter(args).map(into_duckdb), groups=groups)
        )

    def select_dtypes(self, types: list[sqltypes.DuckDBPyType | StrIntoPyType]) -> Self:
        """Select columns from the relation, by filtering based on type(s)."""
        return self._new(self.inner().select_dtypes(types))

    def select_types(self, types: list[sqltypes.DuckDBPyType | StrIntoPyType]) -> Self:
        """Select columns from the relation, by filtering based on type(s)."""
        return self._new(self.inner().select_types(types))

    def set_alias(self, alias: str) -> Self:
        """Rename the relation object to new alias."""
        return self._new(self.inner().set_alias(alias))

    def show(
        self,
        *,
        max_width: SupportsInt | None = None,
        max_rows: SupportsInt | None = None,
        max_col_width: SupportsInt | None = None,
        null_value: str | None = None,
        render_mode: RenderMode | RenderModeLiteral | None = None,
    ) -> None:
        """Display a summary of the data."""
        return self.inner().show(
            max_width=max_width,
            max_rows=max_rows,
            max_col_width=max_col_width,
            null_value=null_value,
            render_mode=render_mode,
        )

    def sort(self, *args: IntoExpr) -> Self:
        """Reorder the relation object by the provided expressions."""
        return self._new(self.inner().sort(*pc.Iter(args).map(into_duckdb)))

    def sql_query(self) -> str:
        """Get the SQL query that is equivalent to the relation."""
        return self.inner().sql_query()

    def std(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the sample standard deviation for a given expression."""
        return self._new(
            self.inner().std(expression, groups, window_spec, projected_columns)
        )

    def stddev(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the sample standard deviation for a given expression."""
        return self._new(
            self.inner().stddev(expression, groups, window_spec, projected_columns)
        )

    def stddev_pop(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the population standard deviation for a given expression."""
        return self._new(
            self.inner().stddev_pop(expression, groups, window_spec, projected_columns)
        )

    def stddev_samp(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the sample standard deviation for a given expression."""
        return self._new(
            self.inner().stddev_samp(expression, groups, window_spec, projected_columns)
        )

    def string_agg(
        self,
        expression: str,
        sep: str = ",",
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Concatenates the values present in a given expression with a separator."""
        return self._new(
            self.inner().string_agg(
                expression, sep, groups, window_spec, projected_columns
            )
        )

    def sum(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the sum of all values present in a given expression."""
        return self._new(
            self.inner().sum(expression, groups, window_spec, projected_columns)
        )

    def tf(self) -> pc.Dict[str, Any]:  # pyright: ignore[reportExplicitAny]
        """Fetch a result as dict of TensorFlow Tensors."""
        return pc.Dict.from_ref(self.inner().tf())

    def to_csv(
        self,
        file_name: str,
        *,
        sep: str | None = None,
        na_rep: str | None = None,
        header: bool | None = None,
        quotechar: str | None = None,
        escapechar: str | None = None,
        date_format: str | None = None,
        timestamp_format: str | None = None,
        quoting: str | int | None = None,
        encoding: CsvEncoding | None = None,
        compression: CsvCompression | None = None,
        overwrite: bool | None = None,
        per_thread_output: bool | None = None,
        use_tmp_file: bool | None = None,
        partition_by: list[str] | None = None,
        write_partition_columns: bool | None = None,
    ) -> None:
        """Write the relation object to a CSV file in 'file_name'."""
        return self.inner().to_csv(
            file_name,
            sep=sep,
            na_rep=na_rep,
            header=header,
            quotechar=quotechar,
            escapechar=escapechar,
            date_format=date_format,
            timestamp_format=timestamp_format,
            quoting=quoting,
            encoding=encoding,
            compression=compression,
            overwrite=overwrite,
            per_thread_output=per_thread_output,
            use_tmp_file=use_tmp_file,
            partition_by=partition_by,
            write_partition_columns=write_partition_columns,
        )

    def to_df(self, *, date_as_object: bool = False) -> pd.DataFrame:
        """Execute and fetch all rows as a pandas DataFrame."""
        return self.inner().to_df(date_as_object=date_as_object)

    def to_parquet(
        self,
        file_name: str,
        *,
        compression: ParquetCompression | None = None,
        field_ids: ParquetFieldsOptions | None = None,
        row_group_size_bytes: int | str | None = None,
        row_group_size: int | None = None,
        overwrite: bool | None = None,
        per_thread_output: bool | None = None,
        use_tmp_file: bool | None = None,
        partition_by: list[str] | None = None,
        write_partition_columns: bool | None = None,
        append: bool | None = None,
        filename_pattern: str | None = None,
        file_size_bytes: str | int | None = None,
    ) -> None:
        """Write the relation object to a Parquet file in 'file_name'."""
        return self.inner().to_parquet(
            file_name,
            compression=compression,
            field_ids=field_ids,
            row_group_size_bytes=row_group_size_bytes,
            row_group_size=row_group_size,
            overwrite=overwrite,
            per_thread_output=per_thread_output,
            use_tmp_file=use_tmp_file,
            partition_by=partition_by,
            write_partition_columns=write_partition_columns,
            append=append,
            filename_pattern=filename_pattern,
            file_size_bytes=file_size_bytes,
        )

    def to_table(self, table_name: str) -> None:
        """Creates a new table named table_name with the contents of the relation object."""
        return self.inner().to_table(table_name)

    def to_view(self, view_name: str, replace: bool = True) -> Self:
        """Creates a view named view_name that refers to the relation object."""
        return self._new(self.inner().to_view(view_name, replace))

    def torch(self) -> pc.Dict[str, Any]:  # pyright: ignore[reportExplicitAny]
        """Fetch a result as dict of PyTorch Tensors."""
        return pc.Dict.from_ref(self.inner().torch())

    def union(self, union_rel: Self) -> Self:
        """Create the set union of this relation object with another relation object in other_rel."""
        return self._new(self.inner().union(union_rel.inner()))

    def unique(self, unique_aggr: str) -> Self:
        """Returns the distinct values in a column."""
        return self._new(self.inner().unique(unique_aggr))

    def update(
        self, set: Mapping[str, IntoExpr], *, condition: IntoExpr = None
    ) -> None:
        """Update the given relation with the provided expressions."""
        return self.inner().update(
            into_duckdb_mapping(set), condition=into_duckdb(condition)
        )

    def value_counts(self, expression: str, groups: str = "") -> Self:
        """Computes the number of elements present in a given expression, also projecting the original expression."""
        return self._new(self.inner().value_counts(expression, groups))

    def var(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the sample variance for a given expression."""
        return self._new(
            self.inner().var(expression, groups, window_spec, projected_columns)
        )

    def var_pop(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the population variance for a given expression."""
        return self._new(
            self.inner().var_pop(expression, groups, window_spec, projected_columns)
        )

    def var_samp(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the sample variance for a given expression."""
        return self._new(
            self.inner().var_samp(expression, groups, window_spec, projected_columns)
        )

    def variance(
        self,
        expression: str,
        groups: str = "",
        window_spec: str = "",
        projected_columns: str = "",
    ) -> Self:
        """Computes the sample variance for a given expression."""
        return self._new(
            self.inner().variance(expression, groups, window_spec, projected_columns)
        )

    def write_csv(
        self,
        file_name: str,
        *,
        sep: str | None = None,
        na_rep: str | None = None,
        header: bool | None = None,
        quotechar: str | None = None,
        escapechar: str | None = None,
        date_format: str | None = None,
        timestamp_format: str | None = None,
        quoting: str | int | None = None,
        encoding: CsvEncoding | None = None,
        compression: CsvCompression | None = None,
        overwrite: bool | None = None,
        per_thread_output: bool | None = None,
        use_tmp_file: bool | None = None,
        partition_by: list[str] | None = None,
        write_partition_columns: bool | None = None,
    ) -> None:
        """Write the relation object to a CSV file in 'file_name'."""
        return self.inner().write_csv(
            file_name,
            sep=sep,
            na_rep=na_rep,
            header=header,
            quotechar=quotechar,
            escapechar=escapechar,
            date_format=date_format,
            timestamp_format=timestamp_format,
            quoting=quoting,
            encoding=encoding,
            compression=compression,
            overwrite=overwrite,
            per_thread_output=per_thread_output,
            use_tmp_file=use_tmp_file,
            partition_by=partition_by,
            write_partition_columns=write_partition_columns,
        )

    def write_parquet(
        self,
        file_name: str,
        *,
        compression: ParquetCompression | None = None,
        field_ids: ParquetFieldsOptions | None = None,
        row_group_size_bytes: str | int | None = None,
        row_group_size: int | None = None,
        overwrite: bool | None = None,
        per_thread_output: bool | None = None,
        use_tmp_file: bool | None = None,
        partition_by: list[str] | None = None,
        write_partition_columns: bool | None = None,
        append: bool | None = None,
        filename_pattern: str | None = None,
        file_size_bytes: str | int | None = None,
    ) -> None:
        """Write the relation object to a Parquet file in 'file_name'."""
        return self.inner().write_parquet(
            file_name,
            compression=compression,
            field_ids=field_ids,
            row_group_size_bytes=row_group_size_bytes,
            row_group_size=row_group_size,
            overwrite=overwrite,
            per_thread_output=per_thread_output,
            use_tmp_file=use_tmp_file,
            partition_by=partition_by,
            write_partition_columns=write_partition_columns,
            append=append,
            filename_pattern=filename_pattern,
            file_size_bytes=file_size_bytes,
        )

    @property
    def alias(self) -> str:
        """Get the name of the current alias."""
        return self.inner().alias

    @property
    def columns(self) -> pc.Vec[str]:
        """Return a list containing the names of the columns of the relation."""
        return pc.Vec.from_ref(self.inner().columns)

    @property
    def description(
        self,
    ) -> pc.Vec[tuple[str, sqltypes.DuckDBPyType, None, None, None, None, None]]:
        """Return the description of the result."""
        return pc.Vec.from_ref(self.inner().description)

    @property
    def dtypes(self) -> pc.Vec[sqltypes.DuckDBPyType]:
        """Return a list containing the types of the columns of the relation."""
        return pc.Vec.from_ref(self.inner().dtypes)

    @property
    def shape(self) -> tuple[int, int]:
        """Tuple of # of rows, # of columns in relation."""
        return self.inner().shape

    @property
    def type(self) -> str:
        """Get the type of the relation."""
        return self.inner().type

    @property
    def types(self) -> pc.Vec[sqltypes.DuckDBPyType]:
        """Return a list containing the types of the columns of the relation."""
        return pc.Vec.from_ref(self.inner().types)
